### ISSUE TITLE
Create v4 branch

### ISSUE THREAD

**Issue by traversaro** [conda-forge/libignition-fuel-tools-feedstock#19]
Hi @conda-forge/libignition-fuel-tools , can we create a `v4` branch either from latest commit in master or from https://github.com/conda-forge/libignition-fuel-tools-feedstock/commit/fc7bc3c9bf3e00da6dc7f51e3c3e7eb02b63bf07 ? 
Once it is created, I will be happy to provide a PR to update the branch to release v4.3.0 . This is necessary to unblock the protobuf314 migration for Gazebo, see https://github.com/conda-forge/libignition-transport4-feedstock/pull/23 and https://github.com/conda-forge/libignition-msgs1-feedstock/pull/21 . 

fyi @xhochy

**Comment by Tobias-Fischer** [comment]
Hi, I just created a new branch from the latest commit in master. Feel free to add you as a maintainer of this feedstock if you want :)

**Comment by traversaro** [comment]
v4.3.0 version bumped in https://github.com/conda-forge/libignition-fuel-tools-feedstock/pull/20 for the v4 branch, and I added the v4 branch for migrations in https://github.com/conda-forge/libignition-fuel-tools-feedstock/pull/21 .
